### ISSUE TITLE
AuthenticationActivity crashes if it starts while the screen is turned off and then turned on

### ISSUE THREAD

**Issue by sladomic** [literacyapp-org/literacyapp-android#308]
Description:
- Turn the screen off and wait for the AuthenticationActivity to start

Expected Result:
- The AuthenticationActivity starts but pauses until the screen is turned on (or maybe we shouldn't even start it?)

Actual Result:
- The app crashes (see log)

Log:
```java
12-30 20:59:57.700 20030-20030/org.literacyapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: org.literacyapp, PID: 20030
                                                                 Theme: themes:{}
                                                                 java.lang.RuntimeException: Unable to resume activity {org.literacyapp/org.literacyapp.authentication.AuthenticationActivity}: java.lang.IllegalThreadStateException: Thread already started
                                                                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3137)
                                                                     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3168)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                  Caused by: java.lang.IllegalThreadStateException: Thread already started
                                                                     at java.lang.Thread.checkNotStarted(Thread.java:849)
                                                                     at java.lang.Thread.start(Thread.java:1059)
                                                                     at org.literacyapp.authentication.AuthenticationActivity.onResume(AuthenticationActivity.java:209)
                                                                     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
                                                                     at android.app.Activity.performResume(Activity.java:6327)
                                                                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3126)
                                                                     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3168) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:148) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5461) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by jo-elimu** [comment]
```
        // Detect if screen is active
        DisplayManager displayManager = (DisplayManager) context.getSystemService(Context.DISPLAY_SERVICE);
        for (Display display : displayManager.getDisplays()) {
            if (display.getState() != Display.STATE_ON) {
                // Skip authentication
            }
        }
```
