### ISSUE TITLE
Bug: AuthenticationActivity crashes on Amazon Fire [2-4h]

### ISSUE THREAD

**Issue by nya-elimu** [literacyapp-org/literacyapp-android#354]
versionCode: 1003009

```
--------- beginning of crash
E/AndroidRuntime( 1108): FATAL EXCEPTION: main
E/AndroidRuntime( 1108): Process: org.literacyapp, PID: 1108
E/AndroidRuntime( 1108): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.literacyapp/org.literacyapp.authentication.AuthenticationActivity}: java.lang.NumberFormatException: Invalid int: "null"
E/AndroidRuntime( 1108): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
E/AndroidRuntime( 1108): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
E/AndroidRuntime( 1108): 	at android.app.ActivityThread.access$900(ActivityThread.java:154)
E/AndroidRuntime( 1108): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
E/AndroidRuntime( 1108): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 1108): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 1108): 	at android.app.ActivityThread.main(ActivityThread.java:5294)
E/AndroidRuntime( 1108): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 1108): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 1108): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime( 1108): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime( 1108): Caused by: java.lang.NumberFormatException: Invalid int: "null"
E/AndroidRuntime( 1108): 	at java.lang.Integer.invalidInt(Integer.java:138)
E/AndroidRuntime( 1108): 	at java.lang.Integer.parseInt(Integer.java:358)
E/AndroidRuntime( 1108): 	at java.lang.Integer.parseInt(Integer.java:334)
E/AndroidRuntime( 1108): 	at java.lang.Integer.valueOf(Integer.java:525)
E/AndroidRuntime( 1108): 	at org.literacyapp.authentication.helper.DetectionHelper.getDisplayTemperatureNight(DetectionHelper.java:184)
E/AndroidRuntime( 1108): 	at org.literacyapp.authentication.AuthenticationActivity.onCreate(AuthenticationActivity.java:80)
E/AndroidRuntime( 1108): 	at android.app.Activity.performCreate(Activity.java:5990)
E/AndroidRuntime( 1108): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime( 1108): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
E/AndroidRuntime( 1108): 	... 10 more
I/WindowManager(  470): Screen frozen for +1s17ms due to AppWindowToken{3e38cbad token=Token{31dcd0c4 ActivityRecord{31ddefd7 u0 org.literacyapp/.authentication.AuthenticationActivity t35}}}
E/[EGL-ERROR](  134): egl_image* _egl_create_image_ANDROID_native_buffer(egl_display*, egl_context*, EGLClientBuffer, EGLint*, void*):593: CHUN try create image with crop 0,0,0,0
E/        (  134): CHUN map external image rgb 1024 x 31
W/ActivityManager(  470):   Force finishing activity 1 org.literacyapp/.authentication.AuthenticationActivity
```

**Comment by sladomic** [comment]
The display_temperature_night is a CM feature. So we either need to detect the OS and disable the function and/or use the Android own equivalent feature.

**Comment by jo-elimu** [comment]
@sladomic The Amazon Fire devices I'm testing on are running CyanogenMod 12.1, while the Pixel C devices are running CyanogenMod 13.0.

**Comment by sladomic** [comment]
So even check the OS version? Aiaiai :)

**Comment by sladomic** [comment]
@jogrimst Please retest since this issue should be fixed with #387

**Comment by jo-elimu** [comment]
@sladomic I tested on Amazon Fire with latest changes, and this Exception occurs after rebooting the device:

```
03-29 06:42:41.670 4217-4217/org.literacyapp I/org.literacyapp.util.RootHelper: runAsRoot
03-29 06:42:41.694 4217-4217/org.literacyapp I/org.literacyapp.util.RootHelper: command: settings --cm get system display_temperature_night
03-29 06:42:42.354 4217-4217/org.literacyapp I/org.literacyapp.util.RootHelper: exitValue: 0
03-29 06:42:42.355 4217-4217/org.literacyapp I/org.literacyapp.util.RootHelper: successMessage: null
03-29 06:42:42.355 4217-4217/org.literacyapp E/org.literacyapp.util.RootHelper: errorMessage: Invalid command: --cm
03-29 06:42:42.357 4217-4217/org.literacyapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: org.literacyapp, PID: 4217
                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{org.literacyapp/org.literacyapp.authentication.AuthenticationActivity}: java.lang.NumberFormatException: Invalid int: "null"
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
                                                                   at android.app.ActivityThread.access$900(ActivityThread.java:154)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
                                                                Caused by: java.lang.NumberFormatException: Invalid int: "null"
                                                                   at java.lang.Integer.invalidInt(Integer.java:138)
                                                                   at java.lang.Integer.parseInt(Integer.java:358)
                                                                   at java.lang.Integer.parseInt(Integer.java:334)
                                                                   at java.lang.Integer.valueOf(Integer.java:525)
                                                                   at org.literacyapp.authentication.helper.DetectionHelper.getDisplayTemperatureNight(DetectionHelper.java:185)
                                                                   at org.literacyapp.authentication.AuthenticationActivity.onCreate(AuthenticationActivity.java:82)
                                                                   at android.app.Activity.performCreate(Activity.java:5990)
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420) 
                                                                   at android.app.ActivityThread.access$900(ActivityThread.java:154) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:135) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5294) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 
```

**Comment by sladomic** [comment]
Ok, then this big is not fixed and would need to be adressed separately. Then it's really because of the CM version.
