### ISSUE TITLE
Bug: IllegalThreadStateException occur when turning on screen [2-4h]

### ISSUE THREAD

**Issue by jo-elimu** [literacyapp-org/literacyapp-android#355]
```
01-23 21:26:47.532 24750-24750/org.literacyapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: org.literacyapp, PID: 24750
                                                                 Theme: themes:{}
                                                                 java.lang.RuntimeException: Unable to resume activity {org.literacyapp/org.literacyapp.authentication.AuthenticationActivity}: java.lang.IllegalThreadStateException: Thread already started
                                                                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3137)
                                                                     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3168)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                  Caused by: java.lang.IllegalThreadStateException: Thread already started
                                                                     at java.lang.Thread.checkNotStarted(Thread.java:849)
                                                                     at java.lang.Thread.start(Thread.java:1059)
                                                                     at org.literacyapp.authentication.AuthenticationActivity.onResume(AuthenticationActivity.java:231)
                                                                     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
                                                                     at android.app.Activity.performResume(Activity.java:6327)
                                                                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3126)
                                                                     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3168) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:148) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5461) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by jo-elimu** [comment]
@sladomic This happened when I turned the screen back on after leaving it idle for a long time. Maybe there was a job already running in the background?
